name: Comment Commands

on:
  issue_comment:
    types: [created]

jobs:
  assign-commenter:
    runs-on: ubuntu-24.04
    if: |
      contains(github.event.comment.body, '/assignme') ||
      contains(github.event.comment.body, '/assign me')
    steps:
      - name: Assigning commenter
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
            -d '{"assignees":["${{ github.event.comment.user.login }}"]}'

  request-issue-framing-improvement:
    runs-on: ubuntu-24.04
    if: |
      contains(github.event.comment.body, '/improve') && (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'COLLABORATOR' ||
        github.event.comment.author_association == 'CONTRIBUTOR'
      )
    steps:
      - name: Request issue framing improvement
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"This issue is put on hold due to low quality. No reviews or fixes will be performed at this time. Eventually, it will be closed. While we appreciate your effort writing, we are not able to further investigate it. Please improve it by writing a better title or providing more details, and you may re-open it."}'

  add-duplicate-label:
    runs-on: ubuntu-24.04
    if: |
      contains(github.event.comment.body, '/duplicate') && (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'COLLABORATOR' ||
        github.event.comment.author_association != 'CONTRIBUTOR'
      )
    steps:
      - name: Add duplicate label
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
            -d '{"labels":["duplicate"]}'
